CREATE TABLE `mushrooms`.`mushrooms_classification` (
  `class` VARCHAR(1) NOT NULL,
  `cap_shape` VARCHAR(1) NULL,
  `cap_surface` VARCHAR(1) NULL,
  `cap_color` VARCHAR(1) NULL,
  `bruises` VARCHAR(1) NULL,
  `odor` VARCHAR(1) NULL,
  `gill_attachment` VARCHAR(1) NULL,
  `gill_spacing` VARCHAR(1) NULL,
  `gill_size` VARCHAR(1) NULL,
  `gill_color` VARCHAR(1) NULL,
  `stalk_shape` VARCHAR(1) NULL,
  `stalk_root` VARCHAR(1) NULL,
  `stalk_surface_above_ring` VARCHAR(1) NULL,
  `stalk_surface_below_ring` VARCHAR(1) NULL,
  `stalk_color_above_ring` VARCHAR(1) NULL,
  `stalk_color_below_ring` VARCHAR(1) NULL,
  `veil_type` VARCHAR(1) NULL,
  `veil_color` VARCHAR(1) NULL,
  `ring_number` VARCHAR(1) NULL,
  `ring_type` VARCHAR(1) NULL,
  `spore_print_color` VARCHAR(1) NULL,
  `population` VARCHAR(1) NULL,
  `habitat` VARCHAR(1) NULL,
  PRIMARY KEY (`class`));
