CREATE TABLE `station` (
  `station_id` INT NOT NULL,
  `name` VARCHAR(256) NULL,
  `lat` DECIMAL(20,6) NULL,
  `long` DECIMAL(20,6) NULL,
  `dockcount` INT NULL,
  `landmark` VARCHAR(45) NULL,
  `installation` DATE NULL,
  PRIMARY KEY (`station_id`));

  CREATE TABLE `station_status` (
  `station_id` INT NOT NULL,
  `bikes_available` INT NULL,
  `docks_available` INT NULL,
  `time` DATETIME NULL);

  CREATE TABLE `trip` (
  `trip_id` INT NOT NULL,
  `duration` INT NULL,
  `start_date` DATETIME NULL,
  `start_station` VARCHAR(128) NULL,
  `start_station_id` INT NULL,
  `end_date` DATETIME NULL,
  `end_station` VARCHAR(128) NULL,
  `end_station_id` INT NULL,
  `bike_id` INT NULL,
  `subscriber_type` VARCHAR(45) NULL,
  `zip_code` INT NULL,
  PRIMARY KEY (`trip_id`));


CREATE TABLE `sfbike`.`weather_summary` (
  `date` DATETIME NOT NULL,
  `region` VARCHAR(45) NOT NULL,
  `fog` INT NOT NULL,
  `rain` INT NOT NULL,
  `snow` INT NOT NULL,
  `snowfallm` DECIMAL(10,2) NOT NULL,
  `snowfalli` DECIMAL(10,2) NOT NULL,
  `snowdepthm` DECIMAL(10,2),
  `snowdepthi` DECIMAL(10,2),
  `hail` INT NOT NULL,
  `thunder` INT NOT NULL,
  `tornado` INT NOT NULL,
  `meantempm` INT NOT NULL,
  `meantempi` INT NOT NULL,
  `meandewptm` INT NOT NULL,
  `meandewpti` INT NOT NULL,
  `meanpressurem` INT NOT NULL,
  `meanpressurei` INT NOT NULL,
  `meanwindspdm` INT NOT NULL,
  `meanwindspdi` INT NOT NULL,
  `meanwdire` INT NOT NULL,
  `meanwdird` INT NOT NULL,
  `meanvism` INT NOT NULL,
  `meanvisi` INT NOT NULL,
  `humidity` INT NOT NULL,
  `maxtempm` INT NOT NULL,
  `maxtempi` INT NOT NULL,
  `mintempm` INT NOT NULL,
  `mintempi` INT NOT NULL,
  `maxhumidity` INT NOT NULL,
  `minhumidity` INT NOT NULL,
  `maxdewptm` INT NOT NULL,
  `maxdewpti` INT NOT NULL,
  `mindewptm` INT NOT NULL,
  `mindewpti` INT NOT NULL,
  `maxpressurem` INT NOT NULL,
  `maxpressurei` DECIMAL(10,2) NOT NULL,
  `minpressurem` INT NOT NULL,
  `minpressurei` DECIMAL(10,2) NOT NULL,
  `maxwspdm` INT NOT NULL,
  `maxwspdi` INT NOT NULL,
  `minwspdm` INT NOT NULL,
  `minwspdi` INT NOT NULL,
  `maxvism` INT NOT NULL,
  `maxvisi` INT NOT NULL,
  `minvism` INT NOT NULL,
  `minvisi` INT NOT NULL,
  `gdegreedays` INT NOT NULL,
  `heatingdegreedays` INT NOT NULL,
  `coolingdegreedays` INT NOT NULL,
  `precipm` DECIMAL(10,2) NOT NULL,
  `precipi` DECIMAL(10,2) NOT NULL
  );


